# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginWidget.ui'
#
# Created: Wed Jul 13 22:46:23 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_LoginWidget(object):
    def setupUi(self, LoginWidget):
        LoginWidget.setObjectName(_fromUtf8("LoginWidget"))
        LoginWidget.resize(299, 342)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LoginWidget.sizePolicy().hasHeightForWidth())
        LoginWidget.setSizePolicy(sizePolicy)
        self.verticalLayout = QtGui.QVBoxLayout(LoginWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formTabs = QtGui.QTabWidget(LoginWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formTabs.sizePolicy().hasHeightForWidth())
        self.formTabs.setSizePolicy(sizePolicy)
        self.formTabs.setObjectName(_fromUtf8("formTabs"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lblUsername = QtGui.QLabel(self.tab)
        self.lblUsername.setObjectName(_fromUtf8("lblUsername"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblUsername)
        self.txtUsername = QtGui.QLineEdit(self.tab)
        self.txtUsername.setObjectName(_fromUtf8("txtUsername"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.txtUsername)
        self.lblPassword = QtGui.QLabel(self.tab)
        self.lblPassword.setObjectName(_fromUtf8("lblPassword"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblPassword)
        self.txtPassword = QtGui.QLineEdit(self.tab)
        self.txtPassword.setEchoMode(QtGui.QLineEdit.Password)
        self.txtPassword.setObjectName(_fromUtf8("txtPassword"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.txtPassword)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnLogin = QtGui.QPushButton(self.tab)
        self.btnLogin.setObjectName(_fromUtf8("btnLogin"))
        self.horizontalLayout.addWidget(self.btnLogin)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.formLayout.setLayout(2, QtGui.QFormLayout.SpanningRole, self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.grpServerNews = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpServerNews.sizePolicy().hasHeightForWidth())
        self.grpServerNews.setSizePolicy(sizePolicy)
        self.grpServerNews.setObjectName(_fromUtf8("grpServerNews"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.grpServerNews)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.scrServerNews = QtGui.QScrollArea(self.grpServerNews)
        self.scrServerNews.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrServerNews.setWidgetResizable(True)
        self.scrServerNews.setObjectName(_fromUtf8("scrServerNews"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 255, 157))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.scrServerNews.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrServerNews)
        self.verticalLayout_2.addWidget(self.grpServerNews)
        self.formTabs.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.lblRegUsername = QtGui.QLabel(self.tab_2)
        self.lblRegUsername.setObjectName(_fromUtf8("lblRegUsername"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblRegUsername)
        self.txtRegUsername = QtGui.QLineEdit(self.tab_2)
        self.txtRegUsername.setObjectName(_fromUtf8("txtRegUsername"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.txtRegUsername)
        self.lblRegPassword = QtGui.QLabel(self.tab_2)
        self.lblRegPassword.setObjectName(_fromUtf8("lblRegPassword"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblRegPassword)
        self.txtRegPassword = QtGui.QLineEdit(self.tab_2)
        self.txtRegPassword.setEchoMode(QtGui.QLineEdit.Password)
        self.txtRegPassword.setObjectName(_fromUtf8("txtRegPassword"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.txtRegPassword)
        self.lblRegConfPwd = QtGui.QLabel(self.tab_2)
        self.lblRegConfPwd.setObjectName(_fromUtf8("lblRegConfPwd"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblRegConfPwd)
        self.txtRegConfPwd = QtGui.QLineEdit(self.tab_2)
        self.txtRegConfPwd.setEchoMode(QtGui.QLineEdit.Password)
        self.txtRegConfPwd.setObjectName(_fromUtf8("txtRegConfPwd"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.txtRegConfPwd)
        self.lblRegEmail = QtGui.QLabel(self.tab_2)
        self.lblRegEmail.setObjectName(_fromUtf8("lblRegEmail"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.lblRegEmail)
        self.txtRegEmail = QtGui.QLineEdit(self.tab_2)
        self.txtRegEmail.setObjectName(_fromUtf8("txtRegEmail"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.txtRegEmail)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.btnRegister = QtGui.QPushButton(self.tab_2)
        self.btnRegister.setObjectName(_fromUtf8("btnRegister"))
        self.horizontalLayout_2.addWidget(self.btnRegister)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.formLayout_2.setLayout(4, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.lblRegHint = QtGui.QLabel(self.tab_2)
        self.lblRegHint.setFrameShape(QtGui.QFrame.Box)
        self.lblRegHint.setFrameShadow(QtGui.QFrame.Raised)
        self.lblRegHint.setMidLineWidth(0)
        self.lblRegHint.setText(_fromUtf8(""))
        self.lblRegHint.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblRegHint.setObjectName(_fromUtf8("lblRegHint"))
        self.verticalLayout_3.addWidget(self.lblRegHint)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.formTabs.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout.addWidget(self.formTabs)

        self.retranslateUi(LoginWidget)
        self.formTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LoginWidget)

    def retranslateUi(self, LoginWidget):
        LoginWidget.setWindowTitle(QtGui.QApplication.translate("LoginWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.lblUsername.setText(QtGui.QApplication.translate("LoginWidget", "Username:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPassword.setText(QtGui.QApplication.translate("LoginWidget", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLogin.setText(QtGui.QApplication.translate("LoginWidget", "Login", None, QtGui.QApplication.UnicodeUTF8))
        self.grpServerNews.setTitle(QtGui.QApplication.translate("LoginWidget", "Server News", None, QtGui.QApplication.UnicodeUTF8))
        self.formTabs.setTabText(self.formTabs.indexOf(self.tab), QtGui.QApplication.translate("LoginWidget", "&Login", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRegUsername.setWhatsThis(QtGui.QApplication.translate("LoginWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Please choose a username for your account.  <span style=\" font-style:italic;\">This is not the name of your character; it is just the name you use to login.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRegUsername.setText(QtGui.QApplication.translate("LoginWidget", "Username:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRegPassword.setWhatsThis(QtGui.QApplication.translate("LoginWidget", "Please choose a unique password that is at least 6 characters long and contains only letters and/or numbers.", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRegPassword.setText(QtGui.QApplication.translate("LoginWidget", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRegConfPwd.setWhatsThis(QtGui.QApplication.translate("LoginWidget", "Please type your password again to help prevent typos.", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRegConfPwd.setText(QtGui.QApplication.translate("LoginWidget", "Confirm Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRegEmail.setWhatsThis(QtGui.QApplication.translate("LoginWidget", "Please enter a valid email address so that we can reset your password if you forget it.", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRegEmail.setText(QtGui.QApplication.translate("LoginWidget", "Email:", None, QtGui.QApplication.UnicodeUTF8))
        self.txtRegEmail.setWhatsThis(QtGui.QApplication.translate("LoginWidget", "An email address to register your account to. Used for verification purposes, and if you forget your password.", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRegister.setText(QtGui.QApplication.translate("LoginWidget", "&Register", None, QtGui.QApplication.UnicodeUTF8))
        self.formTabs.setTabText(self.formTabs.indexOf(self.tab_2), QtGui.QApplication.translate("LoginWidget", "&Register", None, QtGui.QApplication.UnicodeUTF8))

