# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MapEditorProperties.ui'
#
# Created: Fri Jan 07 14:45:58 2011
#      by: PySide uic UI code generator
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MapPropertiesDlg(object):
    def setupUi(self, MapPropertiesDlg):
        MapPropertiesDlg.setObjectName("MapPropertiesDlg")
        MapPropertiesDlg.resize(286, 300)
        self.buttonBox = QtGui.QDialogButtonBox(MapPropertiesDlg)
        self.buttonBox.setGeometry(QtCore.QRect(40, 260, 231, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tabWidget = QtGui.QTabWidget(MapPropertiesDlg)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 268, 241))
        self.tabWidget.setObjectName("tabWidget")
        self.GeneralTab = QtGui.QWidget()
        self.GeneralTab.setObjectName("GeneralTab")
        self.label = QtGui.QLabel(self.GeneralTab)
        self.label.setGeometry(QtCore.QRect(10, 10, 61, 16))
        self.label.setObjectName("label")
        self.MapNameEdit = QtGui.QLineEdit(self.GeneralTab)
        self.MapNameEdit.setGeometry(QtCore.QRect(70, 10, 161, 20))
        self.MapNameEdit.setObjectName("MapNameEdit")
        self.label_6 = QtGui.QLabel(self.GeneralTab)
        self.label_6.setGeometry(QtCore.QRect(10, 40, 46, 14))
        self.label_6.setObjectName("label_6")
        self.WidthSpin = QtGui.QSpinBox(self.GeneralTab)
        self.WidthSpin.setGeometry(QtCore.QRect(49, 36, 42, 22))
        self.WidthSpin.setWrapping(False)
        self.WidthSpin.setFrame(True)
        self.WidthSpin.setMinimum(1)
        self.WidthSpin.setMaximum(999)
        self.WidthSpin.setObjectName("WidthSpin")
        self.label_7 = QtGui.QLabel(self.GeneralTab)
        self.label_7.setGeometry(QtCore.QRect(10, 66, 46, 14))
        self.label_7.setObjectName("label_7")
        self.HeightSpin = QtGui.QSpinBox(self.GeneralTab)
        self.HeightSpin.setGeometry(QtCore.QRect(49, 62, 42, 22))
        self.HeightSpin.setWrapping(False)
        self.HeightSpin.setMinimum(1)
        self.HeightSpin.setMaximum(999)
        self.HeightSpin.setObjectName("HeightSpin")
        self.tabWidget.addTab(self.GeneralTab, "")
        self.BordersTab = QtGui.QWidget()
        self.BordersTab.setObjectName("BordersTab")
        self.label_2 = QtGui.QLabel(self.BordersTab)
        self.label_2.setGeometry(QtCore.QRect(13, 10, 71, 16))
        self.label_2.setObjectName("label_2")
        self.NorthBorderEdit = QtGui.QLineEdit(self.BordersTab)
        self.NorthBorderEdit.setGeometry(QtCore.QRect(81, 10, 130, 20))
        self.NorthBorderEdit.setObjectName("NorthBorderEdit")
        self.NorthBorderBrowse = QtGui.QToolButton(self.BordersTab)
        self.NorthBorderBrowse.setGeometry(QtCore.QRect(210, 10, 25, 20))
        self.NorthBorderBrowse.setObjectName("NorthBorderBrowse")
        self.label_3 = QtGui.QLabel(self.BordersTab)
        self.label_3.setGeometry(QtCore.QRect(13, 40, 71, 16))
        self.label_3.setObjectName("label_3")
        self.EastBorderEdit = QtGui.QLineEdit(self.BordersTab)
        self.EastBorderEdit.setGeometry(QtCore.QRect(81, 40, 130, 20))
        self.EastBorderEdit.setObjectName("EastBorderEdit")
        self.EastBorderBrowse = QtGui.QToolButton(self.BordersTab)
        self.EastBorderBrowse.setGeometry(QtCore.QRect(210, 40, 25, 20))
        self.EastBorderBrowse.setObjectName("EastBorderBrowse")
        self.label_4 = QtGui.QLabel(self.BordersTab)
        self.label_4.setGeometry(QtCore.QRect(13, 70, 71, 16))
        self.label_4.setObjectName("label_4")
        self.SouthBorderEdit = QtGui.QLineEdit(self.BordersTab)
        self.SouthBorderEdit.setGeometry(QtCore.QRect(81, 70, 130, 20))
        self.SouthBorderEdit.setObjectName("SouthBorderEdit")
        self.SouthBorderBrowse = QtGui.QToolButton(self.BordersTab)
        self.SouthBorderBrowse.setGeometry(QtCore.QRect(210, 70, 25, 20))
        self.SouthBorderBrowse.setObjectName("SouthBorderBrowse")
        self.label_5 = QtGui.QLabel(self.BordersTab)
        self.label_5.setGeometry(QtCore.QRect(13, 100, 71, 16))
        self.label_5.setObjectName("label_5")
        self.WestBorderEdit = QtGui.QLineEdit(self.BordersTab)
        self.WestBorderEdit.setGeometry(QtCore.QRect(81, 100, 130, 20))
        self.WestBorderEdit.setObjectName("WestBorderEdit")
        self.WestBorderBrowse = QtGui.QToolButton(self.BordersTab)
        self.WestBorderBrowse.setGeometry(QtCore.QRect(210, 100, 25, 20))
        self.WestBorderBrowse.setObjectName("WestBorderBrowse")
        self.tabWidget.addTab(self.BordersTab, "")

        self.retranslateUi(MapPropertiesDlg)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), MapPropertiesDlg.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), MapPropertiesDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(MapPropertiesDlg)

    def retranslateUi(self, MapPropertiesDlg):
        MapPropertiesDlg.setWindowTitle(QtGui.QApplication.translate("MapPropertiesDlg", "Map Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MapPropertiesDlg", "Map Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.MapNameEdit.setWhatsThis(QtGui.QApplication.translate("MapPropertiesDlg", "The name of the map that is shown to players.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MapPropertiesDlg", "Width:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MapPropertiesDlg", "Height:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.GeneralTab), QtGui.QApplication.translate("MapPropertiesDlg", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MapPropertiesDlg", "North Border:", None, QtGui.QApplication.UnicodeUTF8))
        self.NorthBorderBrowse.setText(QtGui.QApplication.translate("MapPropertiesDlg", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MapPropertiesDlg", "East Border:", None, QtGui.QApplication.UnicodeUTF8))
        self.EastBorderBrowse.setText(QtGui.QApplication.translate("MapPropertiesDlg", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MapPropertiesDlg", "South Border:", None, QtGui.QApplication.UnicodeUTF8))
        self.SouthBorderBrowse.setText(QtGui.QApplication.translate("MapPropertiesDlg", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MapPropertiesDlg", "West Border:", None, QtGui.QApplication.UnicodeUTF8))
        self.WestBorderBrowse.setText(QtGui.QApplication.translate("MapPropertiesDlg", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.BordersTab), QtGui.QApplication.translate("MapPropertiesDlg", "Borders", None, QtGui.QApplication.UnicodeUTF8))

