# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MapEditorProperties.ui'
#
# Created: Fri Apr  8 16:47:01 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MapPropertiesDlg(object):
    def setupUi(self, MapPropertiesDlg):
        MapPropertiesDlg.setObjectName("MapPropertiesDlg")
        MapPropertiesDlg.resize(302, 300)
        self.widget = QtGui.QWidget(MapPropertiesDlg)
        self.widget.setGeometry(QtCore.QRect(10, 10, 281, 276))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(self.widget)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 241))
        self.tabWidget.setObjectName("tabWidget")
        self.GeneralTab = QtGui.QWidget()
        self.GeneralTab.setObjectName("GeneralTab")
        self.widget1 = QtGui.QWidget(self.GeneralTab)
        self.widget1.setGeometry(QtCore.QRect(10, 10, 241, 121))
        self.widget1.setObjectName("widget1")
        self.formLayout = QtGui.QFormLayout(self.widget1)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.widget1)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.MapNameEdit = QtGui.QLineEdit(self.widget1)
        self.MapNameEdit.setObjectName("MapNameEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.MapNameEdit)
        self.label_6 = QtGui.QLabel(self.widget1)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.WidthSpin = QtGui.QSpinBox(self.widget1)
        self.WidthSpin.setWrapping(False)
        self.WidthSpin.setFrame(True)
        self.WidthSpin.setMinimum(1)
        self.WidthSpin.setMaximum(999)
        self.WidthSpin.setObjectName("WidthSpin")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.WidthSpin)
        self.label_7 = QtGui.QLabel(self.widget1)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_7)
        self.HeightSpin = QtGui.QSpinBox(self.widget1)
        self.HeightSpin.setWrapping(False)
        self.HeightSpin.setMinimum(1)
        self.HeightSpin.setMaximum(999)
        self.HeightSpin.setObjectName("HeightSpin")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.HeightSpin)
        self.tabWidget.addTab(self.GeneralTab, "")
        self.BordersTab = QtGui.QWidget()
        self.BordersTab.setObjectName("BordersTab")
        self.widget2 = QtGui.QWidget(self.BordersTab)
        self.widget2.setGeometry(QtCore.QRect(8, 10, 260, 136))
        self.widget2.setObjectName("widget2")
        self.formLayout_2 = QtGui.QFormLayout(self.widget2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtGui.QLabel(self.widget2)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.NorthBorderEdit = QtGui.QLineEdit(self.widget2)
        self.NorthBorderEdit.setObjectName("NorthBorderEdit")
        self.horizontalLayout.addWidget(self.NorthBorderEdit)
        self.NorthBorderBrowse = QtGui.QToolButton(self.widget2)
        self.NorthBorderBrowse.setObjectName("NorthBorderBrowse")
        self.horizontalLayout.addWidget(self.NorthBorderBrowse)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_3 = QtGui.QLabel(self.widget2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.EastBorderEdit = QtGui.QLineEdit(self.widget2)
        self.EastBorderEdit.setObjectName("EastBorderEdit")
        self.horizontalLayout_2.addWidget(self.EastBorderEdit)
        self.EastBorderBrowse = QtGui.QToolButton(self.widget2)
        self.EastBorderBrowse.setObjectName("EastBorderBrowse")
        self.horizontalLayout_2.addWidget(self.EastBorderBrowse)
        self.formLayout_2.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_4 = QtGui.QLabel(self.widget2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.SouthBorderEdit = QtGui.QLineEdit(self.widget2)
        self.SouthBorderEdit.setObjectName("SouthBorderEdit")
        self.horizontalLayout_3.addWidget(self.SouthBorderEdit)
        self.SouthBorderBrowse = QtGui.QToolButton(self.widget2)
        self.SouthBorderBrowse.setObjectName("SouthBorderBrowse")
        self.horizontalLayout_3.addWidget(self.SouthBorderBrowse)
        self.formLayout_2.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_5 = QtGui.QLabel(self.widget2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.WestBorderEdit = QtGui.QLineEdit(self.widget2)
        self.WestBorderEdit.setObjectName("WestBorderEdit")
        self.horizontalLayout_4.addWidget(self.WestBorderEdit)
        self.WestBorderBrowse = QtGui.QToolButton(self.widget2)
        self.WestBorderBrowse.setObjectName("WestBorderBrowse")
        self.horizontalLayout_4.addWidget(self.WestBorderBrowse)
        self.formLayout_2.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.tabWidget.addTab(self.BordersTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(self.widget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(MapPropertiesDlg)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), MapPropertiesDlg.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), MapPropertiesDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(MapPropertiesDlg)

    def retranslateUi(self, MapPropertiesDlg):
        MapPropertiesDlg.setWindowTitle(QtGui.QApplication.translate("MapPropertiesDlg", "Map Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MapPropertiesDlg", "Map Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.MapNameEdit.setWhatsThis(QtGui.QApplication.translate("MapPropertiesDlg", "The name of the map that is shown to players.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MapPropertiesDlg", "Width:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MapPropertiesDlg", "Height:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.GeneralTab), QtGui.QApplication.translate("MapPropertiesDlg", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MapPropertiesDlg", "North Border:", None, QtGui.QApplication.UnicodeUTF8))
        self.NorthBorderBrowse.setText(QtGui.QApplication.translate("MapPropertiesDlg", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MapPropertiesDlg", "East Border:", None, QtGui.QApplication.UnicodeUTF8))
        self.EastBorderBrowse.setText(QtGui.QApplication.translate("MapPropertiesDlg", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MapPropertiesDlg", "South Border:", None, QtGui.QApplication.UnicodeUTF8))
        self.SouthBorderBrowse.setText(QtGui.QApplication.translate("MapPropertiesDlg", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MapPropertiesDlg", "West Border:", None, QtGui.QApplication.UnicodeUTF8))
        self.WestBorderBrowse.setText(QtGui.QApplication.translate("MapPropertiesDlg", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.BordersTab), QtGui.QApplication.translate("MapPropertiesDlg", "Borders", None, QtGui.QApplication.UnicodeUTF8))

